name: Slack Bot (Web API) Action
description: An action to notify Slack using the chat.postMessage API
author: yukin01

inputs:
  status:
    description: Job results. In most use cases, you should specify `job.status`.
    required: true
  github_token:
    description: Personal access token (PAT) used to fetch the repository.
    required: false
    default: ${{ github.token }}
  oauth_token:
    description: |
      Slack's access token. If you're using modern Slack Apps,
      specify the **Bot User OAuth Access Token** which begin with `xoxb-`.
    required: true
  channel:
    description: The channel to be notified of results.
    required: true
  text:
    description: Override main body text of the message.
    required: false
    default: ''
  username:
    description: Override bot's user name.
    required: false
    default: ''
  icon_emoji:
    description: Emoji to use as the icon for this message. Overrides `icon_url`.
    required: false
    default: ''
  icon_url:
    description: URL to an image to use as the icon for this message.
    required: false
    default: ''

runs:
  using: node16
  main: dist/index.js

branding:
  icon: alert-circle
  color: green
